class CustomError(Exception):
    pass

class SpecificError(CustomError):
    pass